# Generated by Django 4.1 on 2022-08-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=40),
        ),
    ]
