# Generated by Django 4.1 on 2022-08-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike_app", "0002_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=100),
        ),
    ]
