# Generated by Django 4.1 on 2022-08-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike_app", "0003_alter_customer_country_alter_customer_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_name", models.CharField(max_length=50, unique=True)),
                ("cost", models.IntegerField()),
            ],
        ),
    ]
