# Generated by Django 4.1 on 2022-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Keyword", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=100)),
                ("State", models.CharField(max_length=100)),
                ("Bedrooms", models.IntegerField()),
                ("max_Price", models.IntegerField()),
            ],
        ),
    ]
