# Generated by Django 4.1 on 2022-08-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate_app", "0002_register"),
    ]

    operations = [
        migrations.DeleteModel(name="Register",),
    ]
