# Generated by Django 4.1 on 2022-08-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate_app", "0003_delete_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.IntegerField()),
                ("Message", models.TextField()),
            ],
        ),
    ]
