# Generated by Django 4.1 on 2022-08-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate_app", "0004_inquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="property",
            field=models.CharField(default=0, max_length=160),
            preserve_default=False,
        ),
    ]
