# Generated by Django 4.1 on 2022-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torquay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date1", models.DateField()),
                ("date2", models.DateField()),
            ],
        ),
    ]
