# Generated by Django 4.1 on 2022-08-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torquay", "0002_vacancies"),
    ]

    operations = [
        migrations.CreateModel(
            name="moreInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
                ("demand_subject", models.CharField(max_length=80)),
                ("details", models.TextField(max_length=600)),
            ],
        ),
    ]
