# Generated by Django 4.1 on 2022-08-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("details", models.CharField(max_length=50)),
                ("has_been_done", models.CharField(default=False, max_length=50)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_completion", models.DateTimeField()),
                ("deadline_date", models.DateTimeField()),
            ],
        ),
    ]
