# Generated by Django 4.1 on 2022-08-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="todoapp.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="date_completion",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="todo", name="details", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="has_been_done",
            field=models.BooleanField(default=False),
        ),
    ]
