# Generated by Django 4.1 on 2022-08-15 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="film", old_name="category", new_name="categories",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="director",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="director",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(model_name="film", name="created_in_country",),
        migrations.AlterField(
            model_name="film", name="release_date", field=models.DateField(),
        ),
        migrations.AddField(
            model_name="film",
            name="created_in_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="films.country",
            ),
        ),
    ]
