# Generated by Django 4.1 on 2022-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Daily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("adress", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=60)),
                ("country", models.CharField(max_length=60)),
            ],
        ),
    ]
