# Generated by Django 4.1 on 2022-08-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gif2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="gifs",),
        migrations.AddField(
            model_name="category",
            name="go",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
